[job]
id = "e06-vm-job"

[vm]
command = "/sbin/busybox"
args = ["sleep", "3600"]
kernel = "/srv/vm/overdrive-testing/kernel"
rootfs = "/srv/vm/overdrive-testing/e06-vcTlAH/rootfs.ext4"

[resources]
cpu_milli = 500
memory_bytes = 134217728
