use std::{collections::BTreeMap, fs::{File, OpenOptions}, io::{Read, Write}, os::fd::{AsRawFd, FromRawFd}, os::unix::fs::OpenOptionsExt, time::{Duration, Instant}};
use serde_json::json;
fn u16n(x:&[u8])->u16 {u16::from_ne_bytes(x[..2].try_into().unwrap())}
fn u32n(x:&[u8])->u32 {u32::from_ne_bytes(x[..4].try_into().unwrap())}
fn attr(t:u16,v:&[u8])->Vec<u8>{let mut b=Vec::new();b.extend(((v.len()+4) as u16).to_ne_bytes());b.extend(t.to_ne_bytes());b.extend(v);while b.len()%4!=0{b.push(0)}b}
fn attrs(b:&[u8])->BTreeMap<u16,Vec<u8>>{let mut m=BTreeMap::new();let mut p=0;while p+4<=b.len(){let l=u16n(&b[p..])as usize;if l<4||p+l>b.len(){break}m.insert(u16n(&b[p+2..])&0x3fff,b[p+4..p+l].to_vec());p+=(l+3)&!3}m}
struct Nl{f:File,seq:u32,requests:u64}
impl Nl{
 fn new()->Self{unsafe{let fd=libc::socket(libc::AF_NETLINK,libc::SOCK_RAW,libc::NETLINK_GENERIC);assert!(fd>=0);let mut a:libc::sockaddr_nl=std::mem::zeroed();a.nl_family=libc::AF_NETLINK as u16;assert_eq!(libc::bind(fd,&a as *const _ as *const libc::sockaddr,std::mem::size_of_val(&a)as u32),0);let t=libc::timeval{tv_sec:5,tv_usec:0};libc::setsockopt(fd,libc::SOL_SOCKET,libc::SO_RCVTIMEO,&t as *const _ as *const _,std::mem::size_of_val(&t)as u32);Self{f:File::from_raw_fd(fd),seq:0,requests:0}}}
 fn req(&mut self,fam:u16,cmd:u8,version:u8,dp:Option<u32>,a:Vec<u8>,dump:bool)->Vec<Vec<u8>>{
  self.seq+=1;self.requests+=1;let mut b=Vec::new();b.extend((16+4+if dp.is_some(){4}else{0}+a.len()).to_ne_bytes()[..4].iter());b.extend(fam.to_ne_bytes());b.extend((if dump{0x301u16}else{5u16}).to_ne_bytes());b.extend(self.seq.to_ne_bytes());b.extend(0u32.to_ne_bytes());b.extend([cmd,version,0,0]);if let Some(d)=dp{b.extend(d.to_ne_bytes())}b.extend(a);
  unsafe{let mut dst:libc::sockaddr_nl=std::mem::zeroed();dst.nl_family=libc::AF_NETLINK as u16;assert_eq!(libc::sendto(self.f.as_raw_fd(),b.as_ptr()as *const _,b.len(),0,&dst as *const _ as *const _,std::mem::size_of_val(&dst)as u32),b.len()as isize)}
  let mut out=Vec::new();loop{let mut r=vec![0u8;1<<20];let len=self.f.read(&mut r).expect("netlink response");r.truncate(len);let mut p=0;while p+16<=r.len(){let l=u32n(&r[p..])as usize;assert!(l>=16&&p+l<=r.len());let t=u16n(&r[p+4..]);let seq=u32n(&r[p+8..]);if seq==self.seq{if t==2{let e=i32::from_ne_bytes(r[p+16..p+20].try_into().unwrap());assert_eq!(e,0,"netlink family={fam} cmd={cmd} request={}",self.requests);return out}if t==3{return out}out.push(r[p+16..p+l].to_vec())}p+=(l+3)&!3}}
 }
 fn family(&mut self,name:&str)->u16{let r=self.req(16,3,2,None,attr(2,format!("{name}\0").as_bytes()),false);u16n(&attrs(&r[0][4..])[&1])}
}
fn emit(v:serde_json::Value){println!("{v}");std::io::stdout().flush().unwrap()}
fn wait(){let mut s=String::new();std::io::stdin().read_line(&mut s).unwrap();assert_eq!(s.trim(),"continue")}
fn mac(i:usize)->[u8;6]{let ip=(0xc6120002u32+i as u32).to_be_bytes();[2,0,ip[0],ip[1],ip[2],ip[3]]}
const GW:[u8;6]=[2,0xaa,0x29,0x50,0,1];
fn checksum(b:&[u8])->u16{let mut s=0u32;for c in b.chunks(2){s+=u16::from_be_bytes([c[0],*c.get(1).unwrap_or(&0)])as u32}while s>>16!=0{s=(s&65535)+(s>>16)}!(s as u16)}
fn echo(i:usize,phase:u16)->Vec<u8>{let mut b=vec![0u8;14+20+8+16];b[..6].copy_from_slice(&GW);b[6..12].copy_from_slice(&mac(i));b[12..14].copy_from_slice(&0x0800u16.to_be_bytes());let ip=&mut b[14..34];ip[0]=0x45;ip[2..4].copy_from_slice(&44u16.to_be_bytes());ip[4..6].copy_from_slice(&phase.to_be_bytes());ip[8]=64;ip[9]=1;ip[12..16].copy_from_slice(&(0xc6120002u32+i as u32).to_be_bytes());ip[16..20].copy_from_slice(&0xc6120001u32.to_be_bytes());let c=checksum(ip);ip[10..12].copy_from_slice(&c.to_be_bytes());let ic=&mut b[34..];ic[0]=8;ic[4..6].copy_from_slice(&0x2950u16.to_be_bytes());ic[6..8].copy_from_slice(&phase.to_be_bytes());ic[8..16].copy_from_slice(&(i as u64).to_be_bytes());ic[16..24].copy_from_slice(b"OVS295!!");let c=checksum(ic);ic[2..4].copy_from_slice(&c.to_be_bytes());b}
fn receive(f:&mut File,expected:&[u8],timeout_ms:i32)->bool{let end=Instant::now()+Duration::from_millis(timeout_ms as u64);while Instant::now()<end{let mut p=libc::pollfd{fd:f.as_raw_fd(),events:libc::POLLIN,revents:0};let left=end.saturating_duration_since(Instant::now()).as_millis()as i32;if unsafe{libc::poll(&mut p,1,left)}<=0{return false}let mut b=[0u8;2048];let n=f.read(&mut b).unwrap();if n==expected.len()&&checksum(&b[14..34])==0{let mut actual=b[..n].to_vec();actual[18..20].copy_from_slice(&expected[18..20]);actual[24..26].copy_from_slice(&expected[24..26]);if actual==expected{return true}}}false}
fn reply(mut b:Vec<u8>)->Vec<u8>{let sm=b[6..12].to_vec();b[6..12].copy_from_slice(&GW);b[..6].copy_from_slice(&sm);let src=b[26..30].to_vec();let dst=b[30..34].to_vec();b[26..30].copy_from_slice(&dst);b[30..34].copy_from_slice(&src);b[22]=64;b[24]=0;b[25]=0;let c=checksum(&b[14..34]);b[24..26].copy_from_slice(&c.to_be_bytes());b[34]=0;b[36]=0;b[37]=0;let c=checksum(&b[34..]);b[36..38].copy_from_slice(&c.to_be_bytes());b}
fn flow(nl:&mut Nl,fam:u16,dp:u32,port:u32,dst:Option<[u8;6]>,output:u32){let mut eth=vec![0u8;12];let mut em=vec![0u8;12];if let Some(m)=dst{eth[6..].copy_from_slice(&m);em[6..].fill(255)}let mut key=attr(3,&port.to_ne_bytes());key.extend(attr(4,&eth));key.extend(attr(6,&0x88b5u16.to_be_bytes()));let mut mask=attr(3,&u32::MAX.to_ne_bytes());if dst.is_some(){mask.extend(attr(4,&em))}let mut a=attr(1|0x8000,&key);a.extend(attr(7|0x8000,&mask));a.extend(attr(2|0x8000,&attr(1,&output.to_ne_bytes())));nl.req(fam,1,1,Some(dp),a,false);}
fn stats(nl:&mut Nl,fam:u16,dp:u32)->serde_json::Value{let r=nl.req(fam,3,2,Some(dp),vec![],false);let a=attrs(&r[0][8..]);let s=&a[&3];json!({"hit":u64::from_ne_bytes(s[0..8].try_into().unwrap()),"missed":u64::from_ne_bytes(s[8..16].try_into().unwrap()),"lost":u64::from_ne_bytes(s[16..24].try_into().unwrap()),"flows":u64::from_ne_bytes(s[24..32].try_into().unwrap())})}
fn main(){let a:Vec<String>=std::env::args().collect();let out=std::path::Path::new(&a[1]);let mut nl=Nl::new();let dpf=nl.family("ovs_datapath");let vpf=nl.family("ovs_vport");let flf=nl.family("ovs_flow");let mut da=attr(1,b"ok295dp\0");da.extend(attr(2,&0u32.to_ne_bytes()));da.extend(attr(5,&0u32.to_ne_bytes()));let r=nl.req(dpf,1,2,Some(0),da,false);let dp=u32n(&r[0][4..]);emit(json!({"event":"dp_ready","pid":std::process::id(),"dp_ifindex":dp,"families":{"datapath":dpf,"vport":vpf,"flow":flf},"packet_execute_requests":0}));wait();
 let mut taps=Vec::new();let ctl=unsafe{File::from_raw_fd(libc::socket(libc::AF_INET,libc::SOCK_DGRAM,0))};let start=Instant::now();let mut ids=Vec::new();
 for count in [4usize,1024,4096,8192,16384]{
  let st=Instant::now();while taps.len()<count{let i=taps.len();let name=format!("ok{:05}",i);let f=OpenOptions::new().read(true).write(true).custom_flags(libc::O_NONBLOCK).open("/dev/net/tun").unwrap();let mut ifr=[0u8;40];ifr[..name.len()].copy_from_slice(name.as_bytes());ifr[16..18].copy_from_slice(&0x1002u16.to_ne_bytes());assert_eq!(unsafe{libc::ioctl(f.as_raw_fd(),0x400454cau64,ifr.as_mut_ptr())},0,"TUNSETIFF {name}");ifr[16..].fill(0);assert_eq!(unsafe{libc::ioctl(ctl.as_raw_fd(),0x8913u64,ifr.as_mut_ptr())},0);let flags=u16n(&ifr[16..])|1;ifr[16..18].copy_from_slice(&flags.to_ne_bytes());assert_eq!(unsafe{libc::ioctl(ctl.as_raw_fd(),0x8914u64,ifr.as_mut_ptr())},0,"link up {name}");let mut va=attr(1,&((i+1)as u32).to_ne_bytes());va.extend(attr(2,&1u32.to_ne_bytes()));va.extend(attr(3,format!("{name}\0").as_bytes()));va.extend(attr(5,&0u32.to_ne_bytes()));let vp=nl.req(vpf,1,1,Some(dp),va,false);let vpa=attrs(&vp[0][8..]);let ifindex=unsafe{libc::if_nametoindex(std::ffi::CString::new(name.clone()).unwrap().as_ptr())};assert_eq!(u32n(&vpa[&1]),(i+1)as u32);ids.push(json!({"index":i,"name":name,"ifindex":ifindex,"kernel_vport":i+1,"owner_fd":f.as_raw_fd(),"mac":mac(i),"ipv4":format!("198.18.{}.{}",((i+2)>>8)&255,(i+2)&255)}));taps.push(f);
   if i==0{let before=stats(&mut nl,dpf,dp);let e=echo(0,99);taps[0].write_all(&e).unwrap();assert!(!receive(&mut taps[0],&reply(e),150));let after=stats(&mut nl,dpf,dp);emit(json!({"event":"cold_unconfigured_drop","before":before,"after":after,"reply_received":false,"upcall_pid":0}));}
   flow(&mut nl,flf,dp,(i+1)as u32,None,0);flow(&mut nl,flf,dp,0,Some(mac(i)),(i+1)as u32);
  }
  let attach_s=st.elapsed().as_secs_f64();let before=stats(&mut nl,dpf,dp);let ts=Instant::now();for phase in [1u16,2]{for i in 0..count{let b=echo(i,phase);let expected=reply(b.clone());taps[i].write_all(&b).unwrap();assert!(receive(&mut taps[i],&expected,1000),"ICMP byte-exact roundtrip index {i}, phase {phase}, population {count}")}}
  let after=stats(&mut nl,dpf,dp);let traffic_s=ts.elapsed().as_secs_f64();std::fs::write(out.join(format!("identities-{count}.json")),serde_json::to_vec(&ids).unwrap()).unwrap();emit(json!({"event":"stage_held","pid":std::process::id(),"tap_fds":taps.len(),"actual_tap_netdevices":count,"kernel_netdev_vports":count,"local_internal_vports":1,"first_and_steady_roundtrips_each_port":2,"byte_exact_icmp_roundtrips":count*2,"attach_and_flow_s":attach_s,"traffic_s":traffic_s,"stats_before":before,"stats_after":after,"elapsed_s":start.elapsed().as_secs_f64(),"packet_execute_requests":0}));wait();
 }
 let before=stats(&mut nl,dpf,dp);let mut k=attr(1|0x8000,&{let mut x=attr(3,&1u32.to_ne_bytes());x.extend(attr(4,&[0u8;12]));x.extend(attr(6,&0x88b5u16.to_be_bytes()));x});k.extend(attr(7|0x8000,&attr(3,&u32::MAX.to_ne_bytes())));nl.req(flf,2,1,Some(dp),k,false);let e=echo(0,100);taps[0].write_all(&e).unwrap();assert!(!receive(&mut taps[0],&reply(e),150));let after=stats(&mut nl,dpf,dp);emit(json!({"event":"removed_flow_drop","held_taps":taps.len(),"before":before,"after":after,"reply_received":false,"packet_execute_requests":0}));wait();nl.req(dpf,2,2,Some(dp),vec![],false);let n=taps.len();drop(taps);emit(json!({"event":"cleaned","released_taps":n,"deleted_exact_datapath":"ok295dp","packet_execute_requests":0,"generic_netlink_configuration_requests":nl.requests}));
}
