//! `cargo xtask verifier-regress` — Tier 4 verifier-complexity
//! regression gate.
//!
//! # Architecture
//!
//! Three concerns, three pure functions, plus a shell-side wrapper:
//!
//! 1. [`parse_baseline_file`] — line-by-line key=value parser that
//!    skips `#`-comment and blank lines; returns one
//!    [`BaselineRecord`] per data line. Format pinned by the
//!    documented shape in `perf-baseline/main/verifier-budget/*.txt`.
//! 2. [`parse_veristat_output`] — same shape parser for veristat
//!    output captured at gate time. Currently identical to the
//!    baseline parser because both consume the same recorded
//!    `key=value` form (the project's baselines were generated by
//!    redirecting veristat-equivalent aya `verified_instruction_count`
//!    output through the same writer; see veristat-service-map.txt
//!    "tool:" comment for the historical note).
//! 3. [`evaluate`] — pure decision fn: given baselines + candidates +
//!    policy, returns [`GateOutcome::Pass`] or `Fail { breaches }`.
//!    No I/O, no subprocess. Self-tested at
//!    `xtask/tests/perf_gate_self_test.rs`.
//!
//! The shell-side wrapper lives in `xtask/src/main.rs::verifier_regress`
//! and chains: discover baselines → `which veristat` → run veristat
//! per program → parse output → call [`evaluate`] → render structured
//! verdict to stderr → exit accordingly.
//!
//! # Why two parsers (baseline vs veristat)
//!
//! Today the parsers are identical; tomorrow veristat might emit
//! `-o csv` or JSON and the candidate parser will diverge. Keeping
//! them as named entry points (rather than a single `parse_kv_lines`)
//! pins the *contract* per source — a future veristat upgrade
//! changes [`parse_veristat_output`] without touching the baseline
//! file shape.
//!
//! # Gate policy
//!
//! Per AC 4 of step 07-01:
//! - **Growth gate**: fail if `measured > baseline * (1 + max_growth_fraction)`.
//!   Default `max_growth_fraction = 0.05` (>5%).
//! - **Ceiling-proximity gate**: fail if `measured >= ceiling *
//!   (1 - ceiling_proximity_fraction)`. Default
//!   `ceiling_proximity_fraction = 0.10`, `ceiling_insns = 1_000_000`
//!   (the kernel `CAP_BPF` complexity ceiling) — i.e. fail when
//!   measured is within 10% of the ceiling.
//!
//! # Numeric precision
//!
//! Verifier instruction counts are `u64` for forward-compat but every
//! recorded baseline is well under 2^53 (the kernel `CAP_BPF` ceiling
//! is `1_000_000`); the `as f64` casts in the gate logic are
//! exact-representable. `clippy::cast_precision_loss` is allowed at
//! the module level for this reason.
//!
//! Both clauses are evaluated per program; either tripping is a
//! breach. A program present in baselines but missing from candidates
//! is a separate `MissingProgram` breach. A candidate without a
//! baseline is *not* a breach — new programs are baselined in their
//! introducing commit; the absence of an entry simply means "no
//! contract yet."

#![allow(
    clippy::cast_precision_loss,
    reason = "verified_insns values are bounded by the 1M CAP_BPF ceiling, well below 2^53; all casts are exact-representable. See module docs."
)]

use std::fmt::Write as _;

use color_eyre::eyre::{Result, WrapErr};

/// One row of `perf-baseline/main/verifier-budget/<prog>.txt`.
///
/// Per-file format documented inline in
/// `veristat-service-map.txt` /
/// `veristat-reverse-nat.txt`: leading `#` comments + one or more
/// `key=value` data lines. The parser keys off `prog=` and
/// `verified_insns=` — every other key (`file=`, `verdict=`) is
/// metadata and is ignored at the gate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BaselineRecord {
    /// Program name (e.g. `xdp_service_map_lookup`). Matches the
    /// `prog=<name>` field in veristat output.
    pub program: String,
    /// Verifier instruction count recorded in the baseline. Matches
    /// the `verified_insns=<N>` field.
    pub verified_insns: u64,
}

/// One row of veristat output captured at gate time.
///
/// Same shape as [`BaselineRecord`] today (both formats are recorded
/// via the same writer per the project's tooling history), but kept
/// as a distinct type so a future veristat-format pivot only touches
/// [`parse_veristat_output`] and call sites, not the baseline-file
/// surface.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VeristatRecord {
    /// Program name (matches [`BaselineRecord::program`] for join).
    pub program: String,
    /// Measured verifier instruction count for this gate run.
    pub verified_insns: u64,
}

/// Threshold policy for the gate. `Default` matches AC 4 of step
/// 07-01: >5% growth, >10% of 1M ceiling.
#[derive(Debug, Clone)]
pub struct GatePolicy {
    /// Fraction of the baseline above which growth is a breach.
    /// 0.05 = >5%.
    pub max_growth_fraction: f64,
    /// Per-program kernel complexity ceiling. `1_000_000` is the
    /// `CAP_BPF` ceiling for kernels 5.10+ (`.claude/rules/testing.md`
    /// § Tier 4 / `BPF_COMPLEXITY_LIMIT_INSNS`).
    pub ceiling_insns: u64,
    /// Fraction of the ceiling: a measurement at or above
    /// `ceiling_insns * (1 - ceiling_proximity_fraction)` is a
    /// breach. 0.10 = within 10% of the ceiling.
    pub ceiling_proximity_fraction: f64,
}

impl Default for GatePolicy {
    fn default() -> Self {
        Self {
            max_growth_fraction: 0.05,
            ceiling_insns: 1_000_000,
            ceiling_proximity_fraction: 0.10,
        }
    }
}

/// Why a program failed the gate. Each variant captures the
/// triggering numbers so the renderer can produce structured
/// per-breach messages without recomputing.
#[derive(Debug, Clone, PartialEq)]
pub enum BreachKind {
    /// `measured > baseline * (1 + max_growth_fraction)`.
    GrowthExceeded {
        /// Threshold fraction the policy was configured with (e.g.
        /// 0.05 for >5%); pinned in the breach so the renderer can
        /// echo it verbatim per slice-07's structured-output KPI.
        threshold_fraction: f64,
    },
    /// `measured >= ceiling * (1 - ceiling_proximity_fraction)`.
    CeilingProximity {
        ceiling_insns: u64,
        /// Threshold fraction the policy was configured with (e.g.
        /// 0.10 for "within 10% of ceiling"); pinned for renderer
        /// symmetry with [`BreachKind::GrowthExceeded`].
        threshold_fraction: f64,
    },
    /// Baseline names a program the candidates do not — typically
    /// the BPF object dropped or renamed a program without updating
    /// the baseline directory. Always a breach: silent baseline
    /// rot is exactly what this gate exists to catch.
    MissingFromCandidates,
}

/// One per program that failed.
#[derive(Debug, Clone, PartialEq)]
pub struct Breach {
    pub program: String,
    pub baseline_insns: u64,
    /// Measured value when present. `None` for
    /// [`BreachKind::MissingFromCandidates`].
    pub measured_insns: u64,
    /// Growth ratio `(measured - baseline) / baseline`. Computed
    /// once and pinned so renderer / test assertions agree on the
    /// value. `0.0` for missing-from-candidates breaches.
    pub growth_fraction: f64,
    pub kind: BreachKind,
}

/// Verdict from [`evaluate`]. The shell-side wrapper translates
/// `Fail` into a non-zero exit; tests and renderers consume the
/// structured form directly.
#[derive(Debug, Clone, PartialEq)]
pub enum GateOutcome {
    Pass,
    Fail { breaches: Vec<Breach> },
}

/// Pure gate decision. Per-step contract pinned by
/// `xtask/tests/perf_gate_self_test.rs`:
/// - 12% growth above the 5% threshold ⇒ Fail with one
///   [`BreachKind::GrowthExceeded`] breach.
/// - 2% growth below the threshold ⇒ Pass.
/// - Measured ≥ 90% of 1M ceiling (and growth alone would not have
///   tripped) ⇒ Fail with one [`BreachKind::CeilingProximity`] breach.
/// - Baseline program missing from candidates ⇒ Fail with one
///   [`BreachKind::MissingFromCandidates`] breach.
pub fn evaluate(
    baselines: &[BaselineRecord],
    candidates: &[VeristatRecord],
    policy: &GatePolicy,
) -> GateOutcome {
    let mut breaches: Vec<Breach> = Vec::new();

    for baseline in baselines {
        let candidate = candidates.iter().find(|c| c.program == baseline.program);
        let Some(candidate) = candidate else {
            breaches.push(Breach {
                program: baseline.program.clone(),
                baseline_insns: baseline.verified_insns,
                measured_insns: 0,
                growth_fraction: 0.0,
                kind: BreachKind::MissingFromCandidates,
            });
            continue;
        };

        let baseline_f = baseline.verified_insns as f64;
        let measured_f = candidate.verified_insns as f64;
        let growth_fraction =
            if baseline.verified_insns == 0 { 0.0 } else { (measured_f - baseline_f) / baseline_f };

        if growth_fraction > policy.max_growth_fraction {
            breaches.push(Breach {
                program: baseline.program.clone(),
                baseline_insns: baseline.verified_insns,
                measured_insns: candidate.verified_insns,
                growth_fraction,
                kind: BreachKind::GrowthExceeded { threshold_fraction: policy.max_growth_fraction },
            });
            continue;
        }

        let ceiling_threshold =
            (policy.ceiling_insns as f64) * (1.0 - policy.ceiling_proximity_fraction);
        if measured_f >= ceiling_threshold {
            breaches.push(Breach {
                program: baseline.program.clone(),
                baseline_insns: baseline.verified_insns,
                measured_insns: candidate.verified_insns,
                growth_fraction,
                kind: BreachKind::CeilingProximity {
                    ceiling_insns: policy.ceiling_insns,
                    threshold_fraction: policy.ceiling_proximity_fraction,
                },
            });
        }
    }

    if breaches.is_empty() { GateOutcome::Pass } else { GateOutcome::Fail { breaches } }
}

/// Parse a `perf-baseline/main/verifier-budget/<prog>.txt` file.
///
/// Skips `#`-comment lines and blank lines; every remaining line
/// MUST contain `prog=<name>` and `verified_insns=<N>` somewhere in
/// its space-separated key=value pairs. Other keys (`file=`,
/// `verdict=`) are ignored.
///
/// The parser is tolerant of extra whitespace and key ordering. It
/// is strict on:
/// - Missing `prog=` ⇒ error.
/// - Missing `verified_insns=` ⇒ error.
/// - Non-integer `verified_insns=` ⇒ error.
pub fn parse_baseline_file(text: &str) -> Result<Vec<BaselineRecord>> {
    let mut records = Vec::new();
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (program, verified_insns) = parse_kv_line(line, lineno + 1)?;
        records.push(BaselineRecord { program, verified_insns });
    }
    Ok(records)
}

/// Parse veristat output captured at gate time. Same shape as
/// [`parse_baseline_file`] today — see module-level docs for the
/// rationale for the separate name.
pub fn parse_veristat_output(text: &str) -> Result<Vec<VeristatRecord>> {
    let mut records = Vec::new();
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (program, verified_insns) = parse_kv_line(line, lineno + 1)?;
        records.push(VeristatRecord { program, verified_insns });
    }
    Ok(records)
}

/// Parse one `key=value` data line into `(prog, verified_insns)`.
/// `lineno` is 1-based and used only for error context.
fn parse_kv_line(line: &str, lineno: usize) -> Result<(String, u64)> {
    let mut prog: Option<String> = None;
    let mut insns: Option<u64> = None;
    for token in line.split_whitespace() {
        let Some((key, value)) = token.split_once('=') else {
            continue;
        };
        match key {
            "prog" => prog = Some(value.to_string()),
            "verified_insns" => {
                let parsed: u64 = value.parse().wrap_err_with(|| {
                    format!("line {lineno}: verified_insns={value:?} not a u64")
                })?;
                insns = Some(parsed);
            }
            _ => {}
        }
    }
    let prog = prog.ok_or_else(|| {
        color_eyre::eyre::eyre!("line {lineno}: missing `prog=<name>` in {line:?}")
    })?;
    let insns = insns.ok_or_else(|| {
        color_eyre::eyre::eyre!("line {lineno}: missing `verified_insns=<N>` in {line:?}")
    })?;
    Ok((prog, insns))
}

/// Render a [`GateOutcome::Fail`] as a structured human-readable
/// report. Format pinned by slice-07: program / metric / baseline /
/// measured / threshold per breach.
///
/// The shell-side wrapper writes this to stderr before exiting
/// non-zero; tests assert on the structured `breaches` directly so
/// this fn is not on the test path. Kept here so the format lives
/// next to the verdict types.
pub fn render_failure(breaches: &[Breach]) -> String {
    let mut out = String::new();
    out.push_str("verifier-regress: gate failed — verifier-budget regression detected\n");
    for breach in breaches {
        match &breach.kind {
            BreachKind::GrowthExceeded { threshold_fraction } => {
                let _ = writeln!(
                    out,
                    "  • {} — verified_insns: baseline={}, measured={}, growth={:.2}% (threshold > {:.0}%)",
                    breach.program,
                    breach.baseline_insns,
                    breach.measured_insns,
                    breach.growth_fraction * 100.0,
                    threshold_fraction * 100.0,
                );
            }
            BreachKind::CeilingProximity { ceiling_insns, threshold_fraction } => {
                let proximity = (breach.measured_insns as f64) / (*ceiling_insns as f64) * 100.0;
                let _ = writeln!(
                    out,
                    "  • {} — verified_insns={} approaches ceiling {} ({:.2}% of ceiling; threshold ≥ {:.0}%)",
                    breach.program,
                    breach.measured_insns,
                    ceiling_insns,
                    proximity,
                    (1.0 - threshold_fraction) * 100.0,
                );
            }
            BreachKind::MissingFromCandidates => {
                let _ = writeln!(
                    out,
                    "  • {} — baseline names this program but veristat output does not (baseline={}); silent baseline rot — re-baseline or remove the file",
                    breach.program, breach.baseline_insns,
                );
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn evaluate_passes_when_candidates_match_baseline_exactly() {
        let baselines = vec![BaselineRecord { program: "x".to_string(), verified_insns: 1000 }];
        let candidates = vec![VeristatRecord { program: "x".to_string(), verified_insns: 1000 }];
        let outcome = evaluate(&baselines, &candidates, &GatePolicy::default());
        assert!(matches!(outcome, GateOutcome::Pass));
    }

    #[test]
    fn evaluate_fails_when_baseline_program_missing_from_candidates() {
        let baselines =
            vec![BaselineRecord { program: "missing_prog".to_string(), verified_insns: 1000 }];
        let candidates: Vec<VeristatRecord> = vec![];
        let outcome = evaluate(&baselines, &candidates, &GatePolicy::default());
        let breaches = match outcome {
            GateOutcome::Pass => panic!("missing program must fail"),
            GateOutcome::Fail { breaches } => breaches,
        };
        assert_eq!(breaches.len(), 1);
        assert!(matches!(breaches[0].kind, BreachKind::MissingFromCandidates));
    }

    #[test]
    fn parse_baseline_file_rejects_line_missing_verified_insns() {
        let text = "file=foo.o prog=bar verdict=success\n";
        let err = parse_baseline_file(text).expect_err("missing verified_insns must error");
        let msg = format!("{err:?}");
        assert!(msg.contains("verified_insns"), "error must name missing field; got {msg}");
    }

    #[test]
    fn parse_baseline_file_rejects_line_missing_prog() {
        let text = "file=foo.o verdict=success verified_insns=42\n";
        let err = parse_baseline_file(text).expect_err("missing prog must error");
        let msg = format!("{err:?}");
        assert!(msg.contains("prog"), "error must name missing field; got {msg}");
    }
}
