[job]
id = "coinflip"

[exec]
command = "/bin/bash"
args = [
    "-c",
    "if (( RANDOM % 2 )); then echo SUCCESS; exit 0; else echo ERROR >&2; exit 1; fi",
]

[resources]
cpu_milli = 100
memory_bytes = 67108864
