#!/usr/bin/env bash
# Install the pinned Quint formal-methods toolchain: the Quint standalone
# binary, a Temurin JDK 21 (Apalache and TLC run on the JVM), and a
# pre-populated QUINT_HOME holding the Apalache distribution and the Rust
# evaluator that Quint would otherwise download on first use.
#
# CONSUMED BY: the `quint` job in .github/workflows/ci.yml.
# infra/lima/overdrive-dev.yaml carries the same pins inline in its
# `param:` block and its Quint provisioning step (Lima templates cannot
# reference a file in a particular checkout); keep the two aligned.
#
# Usage: install-quint.sh <prefix> [<bin-dir>]
#
#   <prefix>/quint/<QUINT_VERSION>/quint   the Quint binary
#   <prefix>/jdk                           Temurin JDK 21
#   <prefix>/quint-home                    QUINT_HOME (Apalache + evaluator)
#   <bin-dir>/quint                        wrapper that defaults QUINT_HOME and
#                                          JAVA_HOME to the paths above, so the
#                                          toolchain works under `sudo env PATH=…`
#                                          without any further environment
#   <bin-dir>/java                         symlink to the JDK's java
#
# <bin-dir> defaults to <prefix>/bin. Idempotent: every artifact is
# checksum-verified on download and skipped when already present.
set -euo pipefail

# Pins. Quint v0.33.0 exists (2026-09-28); v0.32.0 is held because it is
# the version the quint-connect 0.1.2 conformance precedent was validated
# against (Apalache 0.56.1, evaluator v0.6.0). Clears when v0.33.0 is run
# against the specs/quint/** checks and quint-connect.
QUINT_VERSION="v0.32.0"
QUINT_SHA256_AMD64="939b64095b706017f2f202c6f99c860c40be7c31bddc2b98557316e50f42cd7f"
QUINT_SHA256_ARM64="5b23e6f7e6f6b9c870c5ea7d38675e8fc709f4578bcf4a236918414157267a35"
# Apalache version Quint v0.32.0 downloads by default (`quint verify
# --apalache-version` default); used to verify the pre-fetch landed.
APALACHE_VERSION="0.56.1"
JDK_RELEASE="jdk-21.0.12.1+1"
JDK_FILE_VERSION="21.0.12.1_1"
JDK_SHA256_X64="ce79869e1307ed8ee1e2baa86a412b1eb5b75d10a01006d788a6f968bcfaee94"
JDK_SHA256_AARCH64="23e37e026f12f3e706f18938ff611db3032d075b09d0879a25d06718c773e223"

PREFIX="${1:?usage: install-quint.sh <prefix> [<bin-dir>]}"
BIN_DIR="${2:-${PREFIX}/bin}"

case "$(uname -m)" in
  x86_64)
    QARCH=amd64; QSHA="${QUINT_SHA256_AMD64}"
    JARCH=x64; JSHA="${JDK_SHA256_X64}" ;;
  aarch64 | arm64)
    QARCH=arm64; QSHA="${QUINT_SHA256_ARM64}"
    JARCH=aarch64; JSHA="${JDK_SHA256_AARCH64}" ;;
  *) echo "install-quint: unsupported arch $(uname -m)" >&2; exit 1 ;;
esac

QUINT_DIR="${PREFIX}/quint/${QUINT_VERSION}"
JDK_DIR="${PREFIX}/jdk"
QUINT_HOME_DIR="${PREFIX}/quint-home"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

mkdir -p "${QUINT_DIR}" "${QUINT_HOME_DIR}" "${BIN_DIR}"

# --- Quint ------------------------------------------------------------------
if [ ! -x "${QUINT_DIR}/quint" ]; then
  curl -fsSL -o "${WORK}/quint" \
    "https://github.com/quint-co/quint/releases/download/${QUINT_VERSION}/quint-linux-${QARCH}"
  echo "${QSHA}  ${WORK}/quint" | sha256sum -c -
  install -m 0755 "${WORK}/quint" "${QUINT_DIR}/quint"
fi

# --- Temurin JDK 21 ---------------------------------------------------------
if [ ! -x "${JDK_DIR}/bin/java" ]; then
  JDK_TGZ="OpenJDK21U-jdk_${JARCH}_linux_hotspot_${JDK_FILE_VERSION}.tar.gz"
  curl -fsSL -o "${WORK}/jdk.tar.gz" \
    "https://github.com/adoptium/temurin21-binaries/releases/download/${JDK_RELEASE/+/%2B}/${JDK_TGZ}"
  echo "${JSHA}  ${WORK}/jdk.tar.gz" | sha256sum -c -
  rm -rf "${JDK_DIR}"
  mkdir -p "${JDK_DIR}"
  # `legal/` holds only license texts stored as hard links, which virtiofs
  # mounts refuse — skip it.
  tar -xzf "${WORK}/jdk.tar.gz" -C "${JDK_DIR}" --strip-components=1 --exclude='*/legal'
fi

# --- Wrapper + java on PATH -------------------------------------------------
cat > "${BIN_DIR}/quint" <<EOF
#!/bin/sh
# Generated by infra/provision/install-quint.sh — Quint ${QUINT_VERSION}.
export QUINT_HOME="\${QUINT_HOME:-${QUINT_HOME_DIR}}"
export JAVA_HOME="\${JAVA_HOME:-${JDK_DIR}}"
export PATH="\${JAVA_HOME}/bin:\${PATH}"
exec "${QUINT_DIR}/quint" "\$@"
EOF
chmod 0755 "${BIN_DIR}/quint"
ln -sf "${JDK_DIR}/bin/java" "${BIN_DIR}/java"

# --- Pre-fetch Apalache + the Rust evaluator into QUINT_HOME ----------------
# Quint downloads both lazily on first `verify` / `run`. Trigger the
# downloads now, against a trivial bounded spec, so check runs never touch
# the network. A dedicated server port keeps this from attaching to any
# Apalache server another process already runs on Quint's default port.
if [ ! -x "${QUINT_HOME_DIR}/apalache-dist-${APALACHE_VERSION}/apalache/bin/apalache-mc" ] \
   || ! ls -d "${QUINT_HOME_DIR}"/rust-evaluator-* >/dev/null 2>&1; then
  cat > "${WORK}/prefetch.qnt" <<'EOF'
module prefetch {
  var x: int
  action init = x' = 0
  action step = all { x < 2, x' = x + 1 }
  val ok = x >= 0
}
EOF
  (
    cd "${WORK}"
    export TMPDIR="${WORK}"
    QUINT_HOME="${QUINT_HOME_DIR}" "${BIN_DIR}/quint" run prefetch.qnt \
      --invariant=ok --max-samples=1 --max-steps=2 </dev/null
    QUINT_HOME="${QUINT_HOME_DIR}" "${BIN_DIR}/quint" verify prefetch.qnt \
      --invariant=ok --max-steps=2 --server-endpoint=localhost:18821 </dev/null
  )
fi
test -x "${QUINT_HOME_DIR}/apalache-dist-${APALACHE_VERSION}/apalache/bin/apalache-mc"
ls -d "${QUINT_HOME_DIR}"/rust-evaluator-* >/dev/null

# Readable by every user (the Lima VM provisions as root; checks run as the
# `lima` user and as root under `cargo xtask lima run`).
chmod -R a+rX "${PREFIX}"

echo "quint $("${BIN_DIR}/quint" --version)"
"${BIN_DIR}/java" -version 2>&1 | head -n1
ls "${QUINT_HOME_DIR}"
